### ISSUE TITLE
General Page Headers and Footers

### ISSUE THREAD

**Issue by steinwaywhw** [hang-qi/tongji-thesis#1]
Tongji has some additional requirements regarding the header, footer and margins. See xuanke.tongji.edu.cn.

**Comment by hang-qi** [comment]
Under investigation and will be fixed soon. Thanks for reporting!

**Comment by hang-qi** [comment]
Header and footer is supported in 5/21's commit, please check it out.

Note: Left-side gutter line is not provided by far.
