### ISSUE TITLE
Thesis & Translation Template

### ISSUE THREAD

**Issue by steinwaywhw** [hang-qi/tongji-thesis#5]
其实只要把那个报告纸去掉，这个模版就可以用于翻译吧，你要不要考虑一下？只是各个章节的序号，不知道要怎么办，能手动指定这是第几章第几节吧？

**Comment by hang-qi** [comment]
其实报告纸也可以留着，格式基本没有啥变化。重新建一个文档，还用这个模板就行。在主文档里把cover page, abstract, toc 去掉就行了。

**Comment by hang-qi** [comment]
至于指定章节，可以自己重置计数器。比如 \setcounter{section}{3}
